<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdOrder', 'doctrine');

/**
 * BaseAdOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $customer_name
 * @property string $customer_phone
 * @property string $customer_address
 * @property integer $price
 * @property clob $body
 * @property integer $status
 * 
 * @method string  getTitle()            Returns the current record's "title" value
 * @method string  getCustomerName()     Returns the current record's "customer_name" value
 * @method string  getCustomerPhone()    Returns the current record's "customer_phone" value
 * @method string  getCustomerAddress()  Returns the current record's "customer_address" value
 * @method integer getPrice()            Returns the current record's "price" value
 * @method clob    getBody()             Returns the current record's "body" value
 * @method integer getStatus()           Returns the current record's "status" value
 * @method AdOrder setTitle()            Sets the current record's "title" value
 * @method AdOrder setCustomerName()     Sets the current record's "customer_name" value
 * @method AdOrder setCustomerPhone()    Sets the current record's "customer_phone" value
 * @method AdOrder setCustomerAddress()  Sets the current record's "customer_address" value
 * @method AdOrder setPrice()            Sets the current record's "price" value
 * @method AdOrder setBody()             Sets the current record's "body" value
 * @method AdOrder setStatus()           Sets the current record's "status" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_order');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'comment' => 'Tên sản phẩm',
             'length' => 255,
             ));
        $this->hasColumn('customer_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên khách hàng',
             'length' => 255,
             ));
        $this->hasColumn('customer_phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Số điện thoại',
             'length' => 255,
             ));
        $this->hasColumn('customer_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Địa chỉ',
             'length' => 255,
             ));
        $this->hasColumn('price', 'integer', 10, array(
             'type' => 'integer',
             'comment' => 'Giá sản phẩm',
             'length' => 10,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung',
             ));
        $this->hasColumn('status', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Trạng thái xử lý',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}