<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adMassage', 'doctrine');

/**
 * BaseadMassage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image
 * @property string $address
 * @property string $time_open
 * @property string $time_close
 * @property string $keywords
 * @property string $phone
 * @property string $slug
 * @property string $description
 * @property integer $location_id
 * @property integer $rate
 * @property integer $total_view
 * @property string $lat
 * @property string $lng
 * @property boolean $is_active
 * @property boolean $is_home
 * @property integer $priority
 * @property clob $content
 * 
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getImage()       Returns the current record's "image" value
 * @method string    getAddress()     Returns the current record's "address" value
 * @method string    getTimeOpen()    Returns the current record's "time_open" value
 * @method string    getTimeClose()   Returns the current record's "time_close" value
 * @method string    getKeywords()    Returns the current record's "keywords" value
 * @method string    getPhone()       Returns the current record's "phone" value
 * @method string    getSlug()        Returns the current record's "slug" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method integer   getLocationId()  Returns the current record's "location_id" value
 * @method integer   getRate()        Returns the current record's "rate" value
 * @method integer   getTotalView()   Returns the current record's "total_view" value
 * @method string    getLat()         Returns the current record's "lat" value
 * @method string    getLng()         Returns the current record's "lng" value
 * @method boolean   getIsActive()    Returns the current record's "is_active" value
 * @method boolean   getIsHome()      Returns the current record's "is_home" value
 * @method integer   getPriority()    Returns the current record's "priority" value
 * @method clob      getContent()     Returns the current record's "content" value
 * @method adMassage setName()        Sets the current record's "name" value
 * @method adMassage setImage()       Sets the current record's "image" value
 * @method adMassage setAddress()     Sets the current record's "address" value
 * @method adMassage setTimeOpen()    Sets the current record's "time_open" value
 * @method adMassage setTimeClose()   Sets the current record's "time_close" value
 * @method adMassage setKeywords()    Sets the current record's "keywords" value
 * @method adMassage setPhone()       Sets the current record's "phone" value
 * @method adMassage setSlug()        Sets the current record's "slug" value
 * @method adMassage setDescription() Sets the current record's "description" value
 * @method adMassage setLocationId()  Sets the current record's "location_id" value
 * @method adMassage setRate()        Sets the current record's "rate" value
 * @method adMassage setTotalView()   Sets the current record's "total_view" value
 * @method adMassage setLat()         Sets the current record's "lat" value
 * @method adMassage setLng()         Sets the current record's "lng" value
 * @method adMassage setIsActive()    Sets the current record's "is_active" value
 * @method adMassage setIsHome()      Sets the current record's "is_home" value
 * @method adMassage setPriority()    Sets the current record's "priority" value
 * @method adMassage setContent()     Sets the current record's "content" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadMassage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_massage');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên cơ sở',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'comment' => 'ảnh đại diện',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Địa chỉ',
             'length' => 255,
             ));
        $this->hasColumn('time_open', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Thời gian mở cửa',
             'length' => 255,
             ));
        $this->hasColumn('time_close', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Thời gian đóng cửa',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'comment' => 'keywords',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Số điện thoại',
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'comment' => 'link',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'mô tả',
             'length' => 2000,
             ));
        $this->hasColumn('location_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Quận, huyện',
             'length' => 5,
             ));
        $this->hasColumn('rate', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'rate',
             'length' => 5,
             ));
        $this->hasColumn('total_view', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Số lượt xem',
             'length' => 5,
             ));
        $this->hasColumn('lat', 'string', 255, array(
             'type' => 'string',
             'comment' => 'tọa độ latitude',
             'length' => 255,
             ));
        $this->hasColumn('lng', 'string', 255, array(
             'type' => 'string',
             'comment' => 'tọa dộ longtidude',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('is_home', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Hiển thị trang chủ',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Nội dung bài viết',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}