<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adLocation', 'doctrine');

/**
 * BaseadLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property boolean $is_active
 * @property integer $parent_id
 * @property integer $level
 * @property integer $priority
 * 
 * @method string     getName()      Returns the current record's "name" value
 * @method string     getCode()      Returns the current record's "code" value
 * @method boolean    getIsActive()  Returns the current record's "is_active" value
 * @method integer    getParentId()  Returns the current record's "parent_id" value
 * @method integer    getLevel()     Returns the current record's "level" value
 * @method integer    getPriority()  Returns the current record's "priority" value
 * @method adLocation setName()      Sets the current record's "name" value
 * @method adLocation setCode()      Sets the current record's "code" value
 * @method adLocation setIsActive()  Sets the current record's "is_active" value
 * @method adLocation setParentId()  Sets the current record's "parent_id" value
 * @method adLocation setLevel()     Sets the current record's "level" value
 * @method adLocation setPriority()  Sets the current record's "priority" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_location');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Tên tỉnh thành',
             'length' => 255,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Mã tỉnh thành',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'phân cấp chuyên mục',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}