<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('adMassageImage', 'doctrine');

/**
 * BaseadMassageImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_path
 * @property integer $massage_id
 * @property integer $priority
 * @property boolean $is_active
 * 
 * @method string         getFilePath()   Returns the current record's "file_path" value
 * @method integer        getMassageId()  Returns the current record's "massage_id" value
 * @method integer        getPriority()   Returns the current record's "priority" value
 * @method boolean        getIsActive()   Returns the current record's "is_active" value
 * @method adMassageImage setFilePath()   Sets the current record's "file_path" value
 * @method adMassageImage setMassageId()  Sets the current record's "massage_id" value
 * @method adMassageImage setPriority()   Sets the current record's "priority" value
 * @method adMassageImage setIsActive()   Sets the current record's "is_active" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseadMassageImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_massage_image');
        $this->hasColumn('file_path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('massage_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Cơ sở',
             ));
        $this->hasColumn('priority', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'comment' => 'Độ ưu tiên hiển thị',
             'length' => 5,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái hiển thị (0: ko hiển thị, 1: hiển thị)',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}