<?php

/**
 * adMassageTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adMassageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adMassageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adMassage');
    }

    public static function getAllMassage()
    {
        return adMassageTable::getInstance()->createQuery()
            ->fetchArray();
    }

    public static function checkSlug($slug)
    {
        return adMassageTable::getInstance()->createQuery()
            ->where('slug=?', $slug)
            ->fetchArray();
    }

    public static function getListMassage($limit = 8, $offset = 0, $location = false, $all = false)
    {
        if (!$all) {
            $q = adMassageTable::getInstance()->createQuery()
                ->andWhere('is_active=?', 1);
            if ($location)
                $q->andWhere('location_id=?', $location);
            $q->orderBy('priority desc, updated_at desc')
                ->limit($limit)
                ->offset($offset);
            $query = $q->fetchArray();
        } else {
            $rawQuery = "SELECT a.*, b.name as locationName FROM ad_massage a
            LEFT JOIN ad_location b ON a.location_id=b.id
            WHERE b.code = ? AND a.is_active=1
            ORDER BY a.total_view DESC
            LIMIT $limit OFFSET $offset
            ;";
            $q = Doctrine_Manager::getInstance()->getCurrentConnection();
            $query = $q->fetchAssoc($rawQuery, array($location));
        }

        if (!empty($query)) {
            return $query;
        }
        return false;
    }

    public static function getListMassageByLocation($location, $limit)
    {
        $rawQuery = "SELECT a.*, b.name as locationName FROM ad_massage a
        LEFT JOIN ad_location b ON a.location_id=b.id
        WHERE b.code = ? AND a.is_active=1
        ORDER BY a.total_view DESC
        LIMIT $limit
        ;";

//        $rawQuery="SELECT * FROM ad_massage WHERE 1=1
//        AND location_id IN(
//        SELECT id FROM ad_location WHERE CODE=?
//        ) AND is_active=1
//        ORDER BY total_view DESC
//        LIMIT $limit
//        ;";
        $q = Doctrine_Manager::getInstance()->getCurrentConnection();
        $result = $q->fetchAssoc($rawQuery, array($location));
//        $result = $q->fetchAssoc($rawQuery, array('code' => $location, 'limit' => $limit));
        if (!empty($result)) {
            return $result;
        }
        return false;
    }

    public static function countListMassageGroupByLocation()
    {
        $q = adMassageTable::getInstance()->createQuery()
            ->select('location_id, count(location_id)')
            ->andWhere('is_active=1')
            ->groupBy('location_id')
            ->fetchArray();
        if (!empty($q)) {
            $arrLocation = [];
            foreach ($q as $item) {
                $arrLocation['mm_' . $item['location_id']] = $item['count'];
            }
            return $arrLocation;
        }
        return false;

    }
}