<?php

/**
 * adMassageCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class adMassageCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object adMassageCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('adMassageComment');
    }
}