<?php

/**
 * AdOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdOrder');
    }
}